[[messages]]
text = "That page doesn't exist on this world line."
source = "https://myanimelist.net/anime/9253/Steins_Gate"

[[messages]]
text = "Megumin blew up the page you were looking for."
source = "https://myanimelist.net/anime/30831/Kono_Subarashii_Sekai_ni_Shukufuku_wo"

[[messages]]
text = "A witch's labyrinth has swallowed the page you were looking for."
source = "https://myanimelist.net/anime/9756/Mahou_Shoujo_Madoka★Magica"

[[messages]]
text = "Yukko forgot her homework. And the page you were looking for."
source = "https://myanimelist.net/anime/10165/Nichijou"

[[messages]]
text = "The page you were loooking for is busy enjoying some after-school tea time."
source = "https://myanimelist.net/anime/5680/K-ON"

[[messages]]
text = "The page you were looking for ran away with a certain band's guitarist."
source = "https://myanimelist.net/anime/47917/Bocchi_the_Rock"

[[messages]]
text = "The page you were looking for can't communicate."
source = "https://myanimelist.net/anime/48926/Komi-san_wa_Comyushou_desu"

[[messages]]
text = "The page you were looking for is off camping in Izu."
source = "https://myanimelist.net/anime/34798/Yuru_Camp△"

[[messages]]
text = "Anya couldn't find the page you were looking for."
source = "https://myanimelist.net/anime/50265/Spy_x_Family"

[[messages]]
text = "The page you were looking for went cyberpsycho."
source = "https://myanimelist.net/anime/42310/Cyberpunk__Edgerunners"

[[messages]]
text = "The page you were looking for is on a magical journey."
source = "https://myanimelist.net/anime/40571/Majo_no_Tabitabi"

[[messages]]
text = "That page has been erased, deleted, eradicated, and beautified."
source = "https://myanimelist.net/anime/50709/Lycoris_Recoil"
